module.exports = {
  '=': '=',
  'eq': '=',
  '>': '>',
  'gt': '>',
  'greaterThan': '>',
  '<': '<',
  'lt': '<',
  'lessThan': '<',
  '>=': '>=',
  'gte': '>=',
  'greaterThanOrEqualTo': '>=',
  'greaterThanOrEqual': '>=',
  '<=': '<=',
  'lte': '<=',
  'lessThanOrEqualTo': '<=',
  'lessThanOrEqual': '<=',
  '!=': '!=',
  'ne': '!=',
  'notEqualTo': '!=',
  'startsWith': 'STARTSWITH',
  'endsWith': 'ENDSWITH',
  'contains': 'CONTAINS',
  'doesNotContain': 'DOES NOT CONTAIN',
  'in': 'IN',
  'instanceOf': 'INSTANCEOF'
};
