language: node_js

# test on two node.js versions: 0.6 and 0.8
node_js:
  - stable
  - 0.10
  - 0.11
  - 0.12
  - 4
after_script: NODE_ENV=test ./node_modules/.bin/istanbul cover test/integration/runner.js --report lcovonly -- -R spec && cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js && rm -rf ./coverage
